datasetId = 1;
sampleSizeLevel = '1000(200)/';
disp('GCMF/1000(200)');
SetParameter;
expTitle = sprintf('GCMF%d', datasetId);
resultDirectory = sprintf('../../../exp_result/1000(200)/GCMF/%d/', datasetId);
sigma = 0.001;
sigma2 = 0.001;
lambda = 0.001;
gama = 0.001;
numFeatureCluster = 10;
numInstanceCluster = 2;
mkdir(resultDirectory);
isTestPhase = true;
randomTryTime = 5;
numCVFold = 1;
resultFile = fopen(sprintf('%s%s_test.csv', resultDirectory, expTitle), 'w');
fprintf(resultFile, 'numInstanceCluster, numFeatureCluster, sigma, sigma2, lambda, gama, objectiveScore, accuracy, convergeTime\n');
PrepareGCMFExperiment;
main_GCMF_beta;
fclose(resultFile);

sampleSizeLevel = '1000(400)/';
disp('GCMF/1000(400)');
SetParameter;
expTitle = sprintf('GCMF%d', datasetId);
resultDirectory = sprintf('../../../exp_result/1000(400)/GCMF/%d/', datasetId);
sigma = 0.001;
sigma2 = 0.001;
lambda = 0.001;
gama = 0.001;
numFeatureCluster = 10;
numInstanceCluster = 2;
mkdir(resultDirectory);
isTestPhase = true;
randomTryTime = 5;
numCVFold = 1;
resultFile = fopen(sprintf('%s%s_test.csv', resultDirectory, expTitle), 'w');
fprintf(resultFile, 'numInstanceCluster, numFeatureCluster, sigma, sigma2, lambda, gama, objectiveScore, accuracy, convergeTime\n');
PrepareGCMFExperiment;
main_GCMF_beta;
fclose(resultFile);

sampleSizeLevel = '1000(600)/';
disp('GCMF/1000(600)');
SetParameter;
expTitle = sprintf('GCMF%d', datasetId);
resultDirectory = sprintf('../../../exp_result/1000(600)/GCMF/%d/', datasetId);
sigma = 0.001;
sigma2 = 0.001;
lambda = 0.001;
gama = 0.001;
numFeatureCluster = 10;
numInstanceCluster = 2;
mkdir(resultDirectory);
isTestPhase = true;
randomTryTime = 5;
numCVFold = 1;
resultFile = fopen(sprintf('%s%s_test.csv', resultDirectory, expTitle), 'w');
fprintf(resultFile, 'numInstanceCluster, numFeatureCluster, sigma, sigma2, lambda, gama, objectiveScore, accuracy, convergeTime\n');
PrepareGCMFExperiment;
main_GCMF_beta;
fclose(resultFile);

sampleSizeLevel = '1000(800)/';
disp('GCMF/1000(800)');
SetParameter;
expTitle = sprintf('GCMF%d', datasetId);
resultDirectory = sprintf('../../../exp_result/1000(800)/GCMF/%d/', datasetId);
sigma = 0.001;
sigma2 = 0.001;
lambda = 0.001;
gama = 0.001;
numFeatureCluster = 10;
numInstanceCluster = 2;
mkdir(resultDirectory);
isTestPhase = true;
randomTryTime = 5;
numCVFold = 1;
resultFile = fopen(sprintf('%s%s_test.csv', resultDirectory, expTitle), 'w');
fprintf(resultFile, 'numInstanceCluster, numFeatureCluster, sigma, sigma2, lambda, gama, objectiveScore, accuracy, convergeTime\n');
PrepareGCMFExperiment;
main_GCMF_beta;
fclose(resultFile);